service: customers-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-east-2
  stage: aws-dev
  # stage: ${self:custom.profiles.${sls:stage}}
custom:
  profiles:
    dev: aws-dev
    prod: aws-prod

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  create:
    handler: src/index.httpPut
    events:
      - http:
          path: api/put
          method: put
          cors: true

  get:
    handler: src/index.httpGet
    events:
      - http:
          path: api/get/{id}
          method: get
          cors: true
        
  list:
    handler: src/index.httpList
    events:
      - http:
          path: api/list
          method: get
          cors: true
        
  delete:
    handler: src/index.httpDelete
    events:
      - http:
          path: api/delete/{id}
          method: delete
          cors: true